name: Node.js Package
on:
  push:
    branches: [ "main" ]
    paths:
      - "ep_invite_via_email/**"

jobs:
  backend:
    uses: ether/ether-pipelines/.github/workflows/test-and-release-plugins.yml@main
    secrets: inherit
