name: Node.js Package
on:
  push:
    branches: [ "main" ]
    paths:
      - "ep_inline_toolbar/**"

jobs:
  backend:
    uses: ether/ether-pipelines/.github/workflows/test-and-release-plugins-monorepo.yml@main
    secrets: inherit
    with:
       pluginDirectory: 'ep_inline_toolbar'
