name: Node.js Package
on:
  push:
    branches: [ "main" ]
    paths:
      - "ep_list_pads/**"

jobs:
  backend:
    uses: ether/ether-pipelines/.github/workflows/test-and-release-plugins.yml@main
    secrets: inherit
    with:
       pluginDirectory: 'ep_list_pads'
