name: Node.js Package
on:
  push:
    branches: [ "main" ]
    paths:
      - "ep_sticky_attributes/**"

jobs:
  backend:
    uses: ether/ether-pipelines/.github/workflows/test-and-release-plugins-monorepo.yml@main
    secrets: inherit
    with:
       pluginDirectory: 'ep_sticky_attributes'
